name: Muhnro Server Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DEV server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ${{ secrets.DEV_EC2_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            cd /wwwroot/muhnro-server
            git reset --hard
            git clean -fd
            git pull origin develop
            npm ci
            npx prisma migrate deploy
            npx prisma generate
            npm run build
            sudo systemctl restart muhnro-server.service

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to PROD server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_EC2_HOST }}
          username: ${{ secrets.PROD_EC2_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd /wwwroot/muhnro-server
            git reset --hard
            git clean -fd
            git pull origin main
            npm ci
            npx prisma migrate deploy
            npx prisma generate
            npm run build
            sudo systemctl restart muhnro-server.service
